### ISSUE TITLE
BrowserAuthError, when I click the sign in button in the sample.

### ISSUE THREAD

**Issue by abiola-ajibola** [microsoftgraph/msgraph-sample-reactspa#227]
**Describe the bug**
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.

**To Reproduce**
1. Install dependencies and start the app.
2. Click on 'Click here to sign in' button.
3. See error on console and screen:

**Expected behavior**
Redirect to Microsoft sign in page.

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sample-reactspa/assets/52268641/c95a67a1-70ba-4239-9a76-4e4818e04e51)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 119

**Dependency versions**
 - Authentication library (MSAL, etc.) version: "@azure/msal-browser": "^2.38.3",  "@azure/msal-react": "^1.5.12",
 - Graph library (Graph SDK, REST library, etc.) version: "@microsoft/microsoft-graph-client": "^3.0.7",

**Comment by jasonjoh** [comment]
Hi @abiola-ajibola, sorry you're seeing this problem. I've tried to reproduce it and I can't. When you click the button, do you get a pop up like below at all, or is it just straight to the error?

![Screenshot 2024-02-02 091100](https://github.com/microsoftgraph/msgraph-sample-reactspa/assets/8966342/e31494a0-564c-4fba-b6f8-582680e8c000)

Doing some quick searches, I found https://stackoverflow.com/questions/66405214/browserautherror-interaction-in-progress-interaction-is-currently-in-progress (which references https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5807). It looks like the MSAL library sets some stuff in session or browser storage that may be causing this error if it wasn't properly cleaned up. Oddly enough this all seems to be part of the redirect sign in flow, and this app uses the pop-up flow, so not sure why this would be happening here.

Some things you could try:

- Try accessing the app in an incognito/inprivate browser window to eliminate any state that may be interfering.
- Make sure you have pop-ups enabled for the site.
- Check your session and local storage in dev tools for the site to see if there's any data lingering there that shouldn't. For comparison, when I sign out of the site, I don't see anything in storage.

![image](https://github.com/microsoftgraph/msgraph-sample-reactspa/assets/8966342/553ee76d-dd0d-4fac-b7ba-2712e7fc2739)

**Comment by abiola-ajibola** [comment]
Thank you @jasonjoh for the assistance!

I tried in incognito mode and it worked, so I cleared cookies in normal browsing mode and the issue is resolved.

**Comment by jasonjoh** [comment]
Great! Thanks for confirming.
