### ISSUE TITLE
Adding the ability to list Microsoft teams the same way as Microsoft Graph Explorer does

### ISSUE THREAD

**Issue by OthmanAdi** [microsoftgraph/msgraph-sample-reactspa#317]
**Hello world**

Im trying to list Microsoft Teams from the logged in account, and i have been trying for days with it but nothing seems to work, what are the challenges that i need to be able to do that? Outlook365 subscription? Token? API permissions? i have done it all excepts the outlook35 subscription, is that what is missing maybe?

**Comment by jasonjoh** [comment]
This isn't the best place to ask these types of questions. The short answer is - if you can list them in Graph Explorer with your account, you should be able to do it in an app using that same account.
